<?php

	$size_arr = array(__("Small", "krown") => "small", __("Medium", "krown") => "normal",  __("Large", "krown") => "large");

	$target_arr = array(__("Same window", "krown") => "_self", __("New window", "krown") => "_blank");

	$add_css_animation_1 = $add_css_animation_2 = $add_css_animation_3 = array();

	/*

	$add_css_animation_1 = array(
	  "type" => "dropdown",
	  "heading" => __("CSS Animation", "krown"),
	  "param_name" => "css_animation",
	  "admin_label" => true,
	  "value" => array(__("No", "krown") => '', __("Simple fade", "krown") => 'simple', __("Fade from top", "krown") => "top-to-bottom", __("Fade from bottom", "krown") => "bottom-to-top", __("Fade from left", "krown") => "left-to-right", __("Fade from right", "krown") => "right-to-left", __("Appear from center", "krown") => "appear"),
	  "description" => __("Select type of animation if you want this element to be animated when it enters into the browsers viewport. Note: Works only in modern browsers.", "krown")
	);
	$add_css_animation_2 = array(
	  "type" => "dropdown",
	  "heading" => __("Animation speed", "krown"),
	  "param_name" => "css_animation_speed",
	  "value" => array( "0.5s" => 'faster', "1s" => 'default', "2s" => 'slower', "3s" => 'even-slower'),
	  "description" => __("Select the speed of the animation.", "krown"),
	  "dependency" => Array('element' => "css_animation", 'not_empty' => true)

	);
	$add_css_animation_3 = array(
	  "type" => "textfield",
	  "heading" => __("Animation delay", "krown"),
	  "param_name" => "css_animation_delay",
	  "value" => "0",
	  "description" => __("Select the delay of the animation(in milliseconds).", "krown"),
	  "dependency" => Array('element' => "css_animation", 'not_empty' => true)
	);*/

	$icons_arr = array(
		__("None", "krown") => "none",
		__("Aim", "krown") => "krown-icon-aim",
		__("Ajust", "krown") => "krown-icon-ajust",
		__("Asterisk", "krown") => "krown-icon-asterisk",
		__("Award", "krown") => "krown-icon-award",
		__("Bag", "krown") => "krown-icon-bag",
		__("Basket", "krown") => "krown-icon-basket",
		__("Battery", "krown") => "krown-icon-battery",
		__("Beaker", "krown") => "krown-icon-beaker",
		__("Beer", "krown") => "krown-icon-beer",
		__("Behance", "krown") => "krown-icon-behance",
		__("Bell Alt", "krown") => "krown-icon-bell-alt",
		__("Bell", "krown") => "krown-icon-bell",
		__("Block", "krown") => "krown-icon-block",
		__("Book 1", "krown") => "krown-icon-book-1",
		__("Book Open", "krown") => "krown-icon-book-open",
		__("Book", "krown") => "krown-icon-book",
		__("Briefcase", "krown") => "krown-icon-briefcase",
		__("Brush", "krown") => "krown-icon-brush",
		__("Bucket", "krown") => "krown-icon-bucket",
		__("Calendar 1", "krown") => "krown-icon-calendar-1",
		__("Calendar", "krown") => "krown-icon-calendar",
		__("Camera", "krown") => "krown-icon-camera",
		__("Cancel 1", "krown") => "krown-icon-cancel-1",
		__("Cancel", "krown") => "krown-icon-cancel",
		__("Ccw", "krown") => "krown-icon-ccw",
		__("Certificate", "krown") => "krown-icon-certificate",
		__("Chart Area", "krown") => "krown-icon-chart-area",
		__("Chart Bar", "krown") => "krown-icon-chart-bar",
		__("Chart Pie 1", "krown") => "krown-icon-chart-pie-1",
		__("Chart", "krown") => "krown-icon-chart",
		__("Chat", "krown") => "krown-icon-chat",
		__("Clipboard", "krown") => "krown-icon-clipboard",
		__("Clock 1", "krown") => "krown-icon-clock-1",
		__("Clock", "krown") => "krown-icon-clock",
		__("Cloud", "krown") => "krown-icon-cloud",
		__("Cog", "krown") => "krown-icon-cog",
		__("Comment 1", "krown") => "krown-icon-comment-1",
		__("Comment", "krown") => "krown-icon-comment",
		__("Compass", "krown") => "krown-icon-compass",
		__("Cw", "krown") => "krown-icon-cw",
		__("Delicious", "krown") => "krown-icon-delicious",
		__("Desktop", "krown") => "krown-icon-desktop",
		__("Digg 1", "krown") => "krown-icon-digg-1",
		__("Digg", "krown") => "krown-icon-digg",
		__("Down Circle2", "krown") => "krown-icon-down-circle2",
		__("Download Cloud", "krown") => "krown-icon-download-cloud",
		__("Download", "krown") => "krown-icon-download",
		__("Dribbble", "krown") => "krown-icon-dribbble",
		__("Dropbox", "krown") => "krown-icon-dropbox",
		__("Email", "krown") => "krown-icon-email",
		__("Evernote", "krown") => "krown-icon-evernote",
		__("Eye 1", "krown") => "krown-icon-eye-1",
		__("Eye", "krown") => "krown-icon-eye",
		__("Facebook Squared", "krown") => "krown-icon-facebook-squared",
		__("Feather", "krown") => "krown-icon-feather",
		__("Filter", "krown") => "krown-icon-filter",
		__("Fire Station", "krown") => "krown-icon-fire-station",
		__("Fire", "krown") => "krown-icon-fire",
		__("Flag", "krown") => "krown-icon-flag",
		__("Flash 1", "krown") => "krown-icon-flash-1",
		__("Flashlight", "krown") => "krown-icon-flashlight",
		__("Flickr", "krown") => "krown-icon-flickr",
		__("Flight", "krown") => "krown-icon-flight",
		__("Forward", "krown") => "krown-icon-forward",
		__("Gauge", "krown") => "krown-icon-gauge",
		__("Gift", "krown") => "krown-icon-gift",
		__("Github", "krown") => "krown-icon-github",
		__("Globe 1", "krown") => "krown-icon-globe-1",
		__("Globe", "krown") => "krown-icon-globe",
		__("Google Circles", "krown") => "krown-icon-google-circles",
		__("Gplus", "krown") => "krown-icon-gplus",
		__("Graduation Cap", "krown") => "krown-icon-graduation-cap",
		__("Grocery Store", "krown") => "krown-icon-grocery-store",
		__("Hammer", "krown") => "krown-icon-hammer",
		__("Harbor", "krown") => "krown-icon-harbor",
		__("Headphones", "krown") => "krown-icon-headphones",
		__("Heart 1", "krown") => "krown-icon-heart-1",
		__("Heliport", "krown") => "krown-icon-heliport",
		__("Home", "krown") => "krown-icon-home",
		__("Hourglass", "krown") => "krown-icon-hourglass",
		__("Inbox", "krown") => "krown-icon-inbox",
		__("Instagram", "krown") => "krown-icon-instagram",
		__("Key", "krown") => "krown-icon-key",
		__("Lamp", "krown") => "krown-icon-lamp",
		__("Laptop", "krown") => "krown-icon-laptop",
		__("Lastfm", "krown") => "krown-icon-lastfm",
		__("Leaf", "krown") => "krown-icon-leaf",
		__("Left Open 1", "krown") => "krown-icon-left-open-1",
		__("Left Open 2", "krown") => "krown-icon-left-open-2",
		__("Left Open", "krown") => "krown-icon-left-open",
		__("Lightbulb", "krown") => "krown-icon-lightbulb",
		__("Link 1", "krown") => "krown-icon-link-1",
		__("Link", "krown") => "krown-icon-link",
		__("Linkedin", "krown") => "krown-icon-linkedin",
		__("Location", "krown") => "krown-icon-location",
		__("Login", "krown") => "krown-icon-login",
		__("Logout", "krown") => "krown-icon-logout",
		__("Magic", "krown") => "krown-icon-magic",
		__("Magnet 1", "krown") => "krown-icon-magnet-1",
		__("Mail", "krown") => "krown-icon-mail",
		__("Megaphone", "krown") => "krown-icon-megaphone",
		__("Mic", "krown") => "krown-icon-mic",
		__("Minus 1", "krown") => "krown-icon-minus-1",
		__("Minus", "krown") => "krown-icon-minus",
		__("Mobile 1", "krown") => "krown-icon-mobile-1",
		__("Mobile", "krown") => "krown-icon-mobile",
		__("Moon", "krown") => "krown-icon-moon",
		__("Move", "krown") => "krown-icon-move",
		__("Mute", "krown") => "krown-icon-mute",
		__("Network", "krown") => "krown-icon-network",
		__("Note Beamed", "krown") => "krown-icon-note-beamed",
		__("Off", "krown") => "krown-icon-off",
		__("Ok", "krown") => "krown-icon-ok",
		__("Palette", "krown") => "krown-icon-palette",
		__("Paper Plane", "krown") => "krown-icon-paper-plane",
		__("Pencil 1", "krown") => "krown-icon-pencil-1",
		__("Pencil 2", "krown") => "krown-icon-pencil-2",
		__("Pencil", "krown") => "krown-icon-pencil",
		__("Phone 1", "krown") => "krown-icon-phone-1",
		__("Phone", "krown") => "krown-icon-phone",
		__("Picasa", "krown") => "krown-icon-picasa",
		__("Picture 1", "krown") => "krown-icon-picture-1",
		__("Picture", "krown") => "krown-icon-picture",
		__("Pinterest", "krown") => "krown-icon-pinterest",
		__("Play", "krown") => "krown-icon-play",
		__("Plus 1", "krown") => "krown-icon-plus-1",
		__("Plus", "krown") => "krown-icon-plus",
		__("Print", "krown") => "krown-icon-print",
		__("Quote Left", "krown") => "krown-icon-quote-left",
		__("Quote Right", "krown") => "krown-icon-quote-right",
		__("Quote", "krown") => "krown-icon-quote",
		__("Religious Jewish", "krown") => "krown-icon-religious-jewish",
		__("Reply", "krown") => "krown-icon-reply",
		__("Resize Full Alt", "krown") => "krown-icon-resize-full-alt",
		__("Resize Full", "krown") => "krown-icon-resize-full",
		__("Resize Horizontal", "krown") => "krown-icon-resize-horizontal",
		__("Resize Small", "krown") => "krown-icon-resize-small",
		__("Resize Vertical", "krown") => "krown-icon-resize-vertical",
		__("Right Open 1", "krown") => "krown-icon-right-open-1",
		__("Right Open 2", "krown") => "krown-icon-right-open-2",
		__("Right Open Mini", "krown") => "krown-icon-right-open-mini",
		__("Right Open", "krown") => "krown-icon-right-open",
		__("Road", "krown") => "krown-icon-road",
		__("Rocket", "krown") => "krown-icon-rocket",
		__("Rss", "krown") => "krown-icon-rss",
		__("School", "krown") => "krown-icon-school",
		__("Search", "krown") => "krown-icon-search",
		__("Share", "krown") => "krown-icon-share",
		__("Sitemap", "krown") => "krown-icon-sitemap",
		__("Skiing", "krown") => "krown-icon-skiing",
		__("Skype", "krown") => "krown-icon-skype",
		__("Sound", "krown") => "krown-icon-sound",
		__("Soundcloud", "krown") => "krown-icon-soundcloud",
		__("Star", "krown") => "krown-icon-star",
		__("Steam", "krown") => "krown-icon-steam",
		__("Stumbleupon", "krown") => "krown-icon-stumbleupon",
		__("Swimming", "krown") => "krown-icon-swimming",
		__("Tablet", "krown") => "krown-icon-tablet",
		__("Tag", "krown") => "krown-icon-tag",
		__("Tags", "krown") => "krown-icon-tags",
		__("Tape", "krown") => "krown-icon-tape",
		__("Thermometer", "krown") => "krown-icon-thermometer",
		__("Thumbs Down", "krown") => "krown-icon-thumbs-down",
		__("Thumbs Up", "krown") => "krown-icon-thumbs-up",
		__("Tint", "krown") => "krown-icon-tint",
		__("Tools", "krown") => "krown-icon-tools",
		__("Trophy", "krown") => "krown-icon-trophy",
		__("Truck", "krown") => "krown-icon-truck",
		__("Tumblr", "krown") => "krown-icon-tumblr",
		__("Twitter", "krown") => "krown-icon-twitter",
		__("Umbrella", "krown") => "krown-icon-umbrella",
		__("Up Circle2", "krown") => "krown-icon-up-circle2",
		__("Upload Cloud", "krown") => "krown-icon-upload-cloud",
		__("Upload", "krown") => "krown-icon-upload",
		__("User 1", "krown") => "krown-icon-user-1",
		__("User", "krown") => "krown-icon-user",
		__("Users 1", "krown") => "krown-icon-users-1",
		__("Users", "krown") => "krown-icon-users",
		__("Vector Pencil", "krown") => "krown-icon-vector-pencil",
		__("Video", "krown") => "krown-icon-video",
		__("Vimeo", "krown") => "krown-icon-vimeo",
		__("Volume Up", "krown") => "krown-icon-volume-up",
		__("Volume", "krown") => "krown-icon-volume",
		__("Wrench", "krown") => "krown-icon-wrench",
		__("Xing", "krown") => "krown-icon-xing",
		__("Youtube", "krown") => "krown-icon-youtube"
	);

?>